//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HOSPITAL2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class data_Patient
    {
        public int Id { get; set; }
        public Nullable<bool> statues { get; set; }
        public Nullable<System.DateTime> date_time { get; set; }
        public string Serial_Num { get; set; }
    
        public virtual patient patient { get; set; }
        public virtual patient patient1 { get; set; }
    }
}
